# Generated by Django 6.0.5 on 2026-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('tecnologia', models.CharField(max_length=150)),
            ],
        ),
    ]
