# Generated by Django 6.0.5 on 2026-06-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dublador', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='elenco/')),
            ],
        ),
    ]
